## -*- encoding: utf-8 -*-
## This file (hw9.sagetex.sage) was *autogenerated* from hw9.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('hw9', version='2021/10/16 v3.6', version_check=True)
_st_.endofdoc()
